# Sensors const values

#CO2_SSENSOR const values
CO2_SENSOR_MAX_VALUE = 100
CO2_SENSOR_MIN_VALUE = 0

#TEMPERATURE_SENSOR const values
TEMPERATURE_SENSOR_MAX_VALUE = 127
TEMPERATURE_SENSOR_MIN_VALUE = -40

#PH_SENSOR const values
PH_SENSOR_MAX_VALUE = 14
PH_SENSOR_MIN_VALIE = 0



CO2_SENSOR = 'CO2'
TEMPERATURE_SENSOR = 'Temperature'
PH_SENSOR = 'pH'
