# Generated by Django 2.1.5 on 2019-02-04 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_title', models.CharField(max_length=120)),
                ('device_serial_number', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_title', models.CharField(max_length=120)),
                ('hub_serial_number', models.CharField(max_length=16, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hubs',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_title', models.CharField(max_length=120)),
                ('sensor_serial_number', models.CharField(max_length=16, unique=True)),
                ('sensor_data_type', models.CharField(choices=[('pH', 'pH'), ('CO2', 'CO2'), ('Temperature', 'Temperature')], max_length=30)),
                ('sensor_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='hubs_devices_sensors.Device', to_field='device_serial_number')),
            ],
            options={
                'db_table': 'sensors',
            },
        ),
        migrations.CreateModel(
            name='SensorCollectedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_collected', models.DateTimeField()),
                ('sensor_data_value', models.FloatField(blank=True, default=0.1)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_collected_data', to='hubs_devices_sensors.Sensor', to_field='sensor_serial_number')),
            ],
            options={
                'verbose_name': 'Sensor Collected Data',
                'verbose_name_plural': 'Sensor Collected Data',
                'db_table': 'sensor_collected_data',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='device_hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='hubs_devices_sensors.Hub', to_field='hub_serial_number'),
        ),
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together={('sensor_device', 'sensor_data_type')},
        ),
    ]
