# Generated by Django 2.1.5 on 2019-02-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs_devices_sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorcollecteddata',
            name='date_time_collected',
            field=models.DateTimeField(),
        ),
    ]
