# Generated by Django 2.1.5 on 2019-02-01 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubs_devices_sensors', '0002_auto_20190201_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='hubs_devices_sensors.Hub', to_field='hub_serial_number'),
        ),
    ]
