# Generated by Django 2.1.5 on 2019-02-01 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubs_devices_sensors', '0003_auto_20190201_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='hubs_devices_sensors.Device', to_field='device_serial_number'),
        ),
        migrations.AlterField(
            model_name='sensorcollecteddata',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_collected_data', to='hubs_devices_sensors.Sensor'),
        ),
    ]
